package com.ericwathome.currencybuddy.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5C6300)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0EA75)
val md_theme_light_onPrimaryContainer = Color(0xFF1B1D00)
val md_theme_light_secondary = Color(0xFF5E6044)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E5C1)
val md_theme_light_onSecondaryContainer = Color(0xFF1B1D07)
val md_theme_light_tertiary = Color(0xFF3C6659)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEECDC)
val md_theme_light_onTertiaryContainer = Color(0xFF002019)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFFD6)
val md_theme_light_onBackground = Color(0xFF1C1C17)
val md_theme_light_surface = Color(0xFFFEFFD6)
val md_theme_light_onSurface = Color(0xFF1C1C17)
val md_theme_light_surfaceVariant = Color(0xFFE5E3D2)
val md_theme_light_onSurfaceVariant = Color(0xFF47483B)
val md_theme_light_outline = Color(0xFF787869)
val md_theme_light_inverseOnSurface = Color(0xFFF4F1E8)
val md_theme_light_inverseSurface = Color(0xFF31312B)
val md_theme_light_inversePrimary = Color(0xFFC4CE5C)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5C6300)
val md_theme_light_outlineVariant = Color(0xFFC8C7B7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC4CE5C)
val md_theme_dark_onPrimary = Color(0xFF2F3300)
val md_theme_dark_primaryContainer = Color(0xFF454B00)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0EA75)
val md_theme_dark_secondary = Color(0xFFC8C9A6)
val md_theme_dark_onSecondary = Color(0xFF303219)
val md_theme_dark_secondaryContainer = Color(0xFF47492E)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E5C1)
val md_theme_dark_tertiary = Color(0xFFA3D0C0)
val md_theme_dark_onTertiary = Color(0xFF07372C)
val md_theme_dark_tertiaryContainer = Color(0xFF234E42)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEECDC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1C17)
val md_theme_dark_onBackground = Color(0xFFE5E2DA)
val md_theme_dark_surface = Color(0xFF1C1C17)
val md_theme_dark_onSurface = Color(0xFFE5E2DA)
val md_theme_dark_surfaceVariant = Color(0xFF47483B)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C7B7)
val md_theme_dark_outline = Color(0xFF929182)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1C17)
val md_theme_dark_inverseSurface = Color(0xFFE5E2DA)
val md_theme_dark_inversePrimary = Color(0xFF5C6300)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC4CE5C)
val md_theme_dark_outlineVariant = Color(0xFF47483B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFEBF1A2)