name: Android Build and Test

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Copy example public_apikey.properties file and substitute API key
        run: |
          cp public_apikey.properties apikey.properties
          sed -i "s/\".*\"/\"${{ secrets.API_KEY }}\"/" apikey.properties

      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt

      - name: Copy example public_apikey.properties file and substitute API key
        run: |
          cp public_apikey.properties apikey.properties
          sed -i "s/\".*\"/\"${{ secrets.API_KEY }}\"/" apikey.properties

      - name: Run tests with Gradle
        run: ./gradlew test


